### PR TITLE
switch to colored itemstacks

### PR DESCRIPTION
**Pull request by VanessaE**
with full crafting recipes
(requires Unified Dyes commit 2a816534 or later)

Your fork seems to be the primary one these days, so I'm submitting this to you :smiley:

### CODE REVIEW

**Comment by VanessaE** [comment]
@sofar preemptive \*poke\*  to fork this mod and this PR to minetest-mods :smiley:

**Comment by andersje** [comment]
Looks good!  Sorry for delay, got distracted with meatspace things.  Thanks for the addition, @VanessaE 

I'd love to, btw, kick this over to someone more active in the community.  :)

**Comment by sofar** [comment]
So we have https://github.com/minetest-mods/

effectively it's a safety net so that we don't endlessly have to refork projects. If people are active, everyone can send pull requests and either the author, maintainer or assigned developers can merge them. If those are not around, several senior minetest developers help out by reviewing changes and maintaining mods where the author isn't around anymore.  We even can adjust forum links to make sure people find the right location of the maintained versions.

Up to you to 'move' your tree over or not. You'd keep commit access, of course, we actually want you to stay around. But if you don't, that's OK too.

**Comment by andersje** [comment]
That would be very fantastic...What's the best way for me to go about this?   @sofar should I reopen the xfer-request for this repo to go to you?   Should I get added to minetest-mods, and then transfer the ownership of this repo to that org?   Any advice is much appreciated.

**Comment by sofar** [comment]
> should I reopen the xfer-request for this repo to go to you?

yes, that's the easiest. Make sure to ping me in advance, the transfers expire relatively quickly and I've got a huge backlog. Best is probably to ping me in IRC.

**Pull request merged**
