### PR TITLE
Many changes, please see commit log :P

### PR DESCRIPTION
**Pull request by VanessaE**
There have been many changes in my fork, mostly in support of param2 colorization and better use of Unified Dyes.

### CODE REVIEW

**Comment by andersje** [comment]
big changes indeed!  I need to update some of my servers shortly to run the new versions of minetest :)

**Comment by VanessaE** [comment]
cheers :smile: 

You should consider putting this mod under the purview of the minetest-mods team.  To do that, initiate a repository transfer to user "sofar", and he'll do the rest.  You'll retain write authority in the new repo, as will he, I, and other minetest-mods team members.

Should make less work for you, and less time spent out of date :wink:

**Comment by sofar** [comment]
so, normally I don't accept random repo transfers, and I always do a review to see if the mod is meeting the requirements.

In this case, license and code all look OK, but your branch is a fork. The original author is still active, and, out of politeness, I would like to ask  @doyousketch2 first to OK the move of *his* original mod code to @minetest-mods (through @sofar of course), and then grant @vanessae and @andersje maintenance permissions so they can continue to maintain the mod.

The reason we do this is to *notify* the original authors that we have a nice place for their code to be collectively maintained, and usually they agree. Seeing that @doyousketch2 is still active on github, he will hopefully respond in here.

Of course, ideally we have this discussion in an issue in https://github.com/minetest-mods/minetest-mods.github.io, but this thread will do just fine I suppose :)

**Comment by andersje** [comment]
Sure, I'm fine with that.  At the time my code was forked, he had been inactive for some time.  No disrespect was intended.  =)

**Comment by sofar** [comment]
@andersje of course, I wasn't implying that - I'm merely following and explaining the rules we set for minetest-mods.

**Pull request merged**
